name: hu_guide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_native_splash: ^2.4.7
  fluttertoast: ^9.0.0
  http: ^1.5.0
  icons_launcher: ^3.0.3
  latlong2: ^0.9.1
  loading_indicator: ^3.1.1
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  syncfusion_flutter_pdfviewer: ^31.2.10
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

icons_launcher:
  image_path: "assets/huguide.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/colleges/
    - assets/clubs/
    - assets/events/
    - assets/resources/
